/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIDesigns;
import Method.Student;
import Method.StudentDetails;
import static UIDesigns.Studentpayment.jTable1;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.JOptionPane;
/**
 *
 * @author Home-PC
 */
public class Attendance extends javax.swing.JPanel {
       private Vector<String> header;
         private Vector<Vector<String>> data; //Used for data from database
    /**
     * Creates new form Class_view
     */
    public Attendance() {
        initComponents();
     getStudents();
loadStudentAttenTables();
          
    }
private void getStudents() {
        StudentDetails dao = new StudentDetails();
        ArrayList codeList = dao.getStudent();

        Iterator i = codeList.iterator();

        while (i.hasNext()) {
            jComboBox2.addItem(i.next());
        }

        String cscode = jComboBox2.getSelectedItem().toString();

    }
private void loadStudentAttenTables() {
        header = new Vector<String>();
        header.add("AtteId");
        header.add("sid");
        header.add("StudentName");
      header.add("Course");
      header.add("Date");
       header.add("Present");
        StudentDetails dao = new StudentDetails();
        data = dao.getAttenDetails();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
        jScrollPane1.setViewportView(jTable1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField9 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dateCombo = new org.freixas.jcalendar.JCalendarCombo();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1090, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField9.setEnabled(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 540, 40));

        jLabel3.setText("Course");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel8.setText("Student ID");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 540, 37));

        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 540, 40));

        jLabel2.setText("Student Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        dateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboActionPerformed(evt);
            }
        });
        add(dateCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 540, 40));

        jLabel4.setText("Date");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jRadioButton2.setText("present");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jRadioButton3.setText("Absent");
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jLabel5.setText("Present");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 1010, 310));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 100, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here
        String sid = jComboBox2.getSelectedItem().toString();
    int sids = Integer.valueOf(sid);


    StudentDetails dao = new StudentDetails();
    Student sp = dao.searchStudentDetails(sids);

    /* brandnametxt.setText(d.getName());
    suppIDbrandcmb.setSelectedItem(d.getSupplierId());
    supbrandNametxt.setText(d.getSupplierName());
    branddescriptiontxt.setText(d.getDescription());*/
    jComboBox2.setSelectedItem(String.valueOf(sp.getsid()));
    jTextField5.setText(sp.getfname());
    jTextField9.setText(sp.getCourse());

    
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField5KeyPressed

    private void dateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateComboActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      String gender = null;
        if(jRadioButton2.isSelected()) 
        gender="Present";
else if(jRadioButton3.isSelected()) 
        gender="Absent";
       
        String sid = jComboBox2.getSelectedItem().toString();
         int sids = Integer.valueOf(sid);
        String Name = jTextField5.getText();
         String Date = dateCombo.getSelectedItem().toString();
        String Course = jTextField9.getText();
        
        Component rootPane = null;
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Save This Recode?");

        if (x == 0) {
            Student cs = new Student(sids,Name,Date,Course,gender);

            StudentDetails dao = new StudentDetails();
            dao. addAttendance(cs);
            jComboBox2.setSelectedItem("00");
            jTextField5.setText("");
dateCombo.setSelectedItem("00");
    jTextField9.setText("");
            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
           jComboBox2.setSelectedItem("00");
            jTextField5.setText("");
dateCombo.setSelectedItem("00");
    jTextField9.setText("");
    
        } else {
           jComboBox2.setSelectedItem("00");
            jTextField5.setText("");
dateCombo.setSelectedItem("00");
    jTextField9.setText("");
            ;
        }



    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.freixas.jcalendar.JCalendarCombo dateCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
