/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIDesigns;
import Method.LeacherDetails;
import java.util.ArrayList;
import Method.Lectures;
import java.util.Iterator;
import Method.ClassM;
import Method.ClassDetails;
import java.util.Vector;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Home-PC
 */
public class ClassDe extends javax.swing.JPanel {
    private Component rootPane;
 private Vector<Vector<String>> data;
    private Vector<String> header;
      
    /**
     * Creates new form Class
     */
    public ClassDe() {
        initComponents();
          fillCourseNames();
          header = new Vector<String>();
         header.add("Class_ID");
        header.add("Class_Name");
          header.add("Schedule");
          header.add("Lecturer_Name"); 
          header.add("Class_Time_In");
          header.add("Class_Time_out");
          
        loadCourseTable();
    }
    private void loadCourseTable() {
  ClassDetails dao = new ClassDetails();
        data = dao.getClassDetails();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
        jScrollPane1.setViewportView(jTable1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        Lecture_Name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Update = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Schedule = new javax.swing.JTextField();
        Time_Out = new javax.swing.JTextField();
        Class_Name = new javax.swing.JTextField();
        Class_IDs = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Time_In = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 153, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Class Details");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1090, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 690, 460));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lecturer Details"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 221, 30));
        jPanel1.add(Lecture_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 220, 30));

        jLabel5.setText("Lecture Id");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel10.setText("Lecture Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1040, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Class Details"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Apps-system-software-update-icon.png"))); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel2.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, 40));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home-PC\\Documents\\StudentRegSystem\\src\\Image\\1463780845_hammer_screwdriver.png")); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, 40));
        jPanel2.add(Schedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 220, 30));

        Time_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Time_OutActionPerformed(evt);
            }
        });
        jPanel2.add(Time_Out, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 220, 30));
        jPanel2.add(Class_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 220, 30));
        jPanel2.add(Class_IDs, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 220, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Class ID");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        jLabel4.setText("Class Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel7.setText("Time Out");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel8.setText("Schedule");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel2.add(Time_In, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 220, 30));

        jLabel9.setText("Time In");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete-icon.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Refresh-icon.png"))); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 280, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 340, 450));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 1090, 660));
    }// </editor-fold>//GEN-END:initComponents
 private void fillCourseNames() {
       LeacherDetails dao = new LeacherDetails();
        ArrayList NameList = dao.getLeacher();

        Iterator i = NameList.iterator();

        while (i.hasNext()) {
            jComboBox1.addItem(i.next());
        }

        String csName = jComboBox1.getSelectedItem().toString();
 }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String Class_ID  = Class_IDs.getText();
        int Class_ID1 = Integer.valueOf(Class_ID);
        String Class_Names = Class_Name.getText();
         String lec_id = jComboBox1.getSelectedItem().toString();
        int lec_id1 = Integer.valueOf(lec_id);
         String Lecturer_Name = Lecture_Name.getText();
         String Class_Time_In = Time_In.getText(); 
         String Class_Time_out = Time_Out.getText();
         String Schedules = Schedule.getText();
        
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Save This Recode?");

        if (x == 0) {
            ClassM cs = new ClassM(Class_ID1,Class_Names,lec_id1,Lecturer_Name,Class_Time_In,Class_Time_out,Schedules);

            ClassDetails dao = new ClassDetails();
            dao. addClass(cs);
            Class_IDs.setText("");
            Class_Name.setText("");
            jComboBox1.setSelectedItem("00");
            Lecture_Name.setText("");
            Time_In.setText("");
            Time_Out.setText("");
             Schedule.setText("");
            

            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
             Class_IDs.setText("");
            Class_Name.setText("");
            jComboBox1.setSelectedItem("00");
            Lecture_Name.setText("");
            Time_Out.setText("");
             Time_In.setText("");
            Time_Out.setText("");
             Schedule.setText("");;
        } else {
             Class_IDs.setText("");
            Class_Name.setText("");
            jComboBox1.setSelectedItem("00");
            Lecture_Name.setText("");
            Time_Out.setText("");
             Time_In.setText("");
            Time_Out.setText("");
             Schedule.setText("");
             
            ;
        }



    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
             String Id = jComboBox1.getSelectedItem().toString();
        int supid = Integer.valueOf(Id);

       LeacherDetails dao = new LeacherDetails();
       Lectures sp = dao.searchDetails(supid);

        /* brandnametxt.setText(d.getName());
         suppIDbrandcmb.setSelectedItem(d.getSupplierId());
         supbrandNametxt.setText(d.getSupplierName());
         branddescriptiontxt.setText(d.getDescription());*/
     jComboBox1.setSelectedItem(String.valueOf(sp.getlec_id()));
       Lecture_Name.setText(sp.getfname()); 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void Time_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Time_OutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Time_OutActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
      String Class_ID  = Class_IDs.getText();
        int Class_ID1 = Integer.valueOf(Class_ID);
        String Class_Names = Class_Name.getText();
         String lec_id = jComboBox1.getSelectedItem().toString();
        int lec_id1 = Integer.valueOf(lec_id);
         String Schedules = Schedule.getText();
         String Lecturer_Name = Lecture_Name.getText();
         String Class_Time_In = Time_In.getText(); 
         String Class_Time_out = Time_Out.getText();
        
      
    int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Change This Recode?");

        if (x == 0) {
            /* EmployeeDetails em;
            em = new EmployeeDetails(emppid, lname, con1, con2, address, des);

            dao.updateEmployee(em);
            *
            *
            *
            */
            ClassM cs = new ClassM(Class_ID1,Class_Names,lec_id1,Lecturer_Name,Class_Time_In,Class_Time_out,Schedules);

             ClassDetails dao = new ClassDetails();
            dao. updateClass(cs);
            Class_IDs.setText("");
            Class_Name.setText("");
            jComboBox1.setSelectedItem("00");
            Lecture_Name.setText("");
            Time_In.setText("");
            Time_Out.setText("");
             Schedule.setText("");
             
            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
             Class_IDs.setText("");
            Class_Name.setText("");
            jComboBox1.setSelectedItem("00");
            Lecture_Name.setText("");
            Time_In.setText("");
            Time_Out.setText("");
             Schedule.setText("");
        } else {
           Class_IDs.setText("");
            Class_Name.setText("");
            jComboBox1.setSelectedItem("00");
            Lecture_Name.setText("");
            Time_In.setText("");
            Time_Out.setText("");
             Schedule.setText("");
            ;
        }        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          String Class_ID  = Class_IDs.getText();
        int Class_ID1 = Integer.valueOf(Class_ID);
        String Class_Names = Class_Name.getText();
         String lec_id = jComboBox1.getSelectedItem().toString();
        int lec_id1 = Integer.valueOf(lec_id);
         String Schedules = Schedule.getText();
         String Lecturer_Name = Lecture_Name.getText();
         String Class_Time_In = Time_In.getText(); 
         String Class_Time_out = Time_Out.getText();
        
      
    int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Change This Recode?");

        if (x == 0) {
            /* EmployeeDetails em;
            em = new EmployeeDetails(emppid, lname, con1, con2, address, des);

            dao.updateEmployee(em);
            *
            *
            *
            */
            ClassM cs = new ClassM(Class_ID1,Class_Names,lec_id1,Lecturer_Name,Class_Time_In,Class_Time_out,Schedules);

             ClassDetails dao = new ClassDetails();
            dao. deleteclass(cs);
            Class_IDs.setText("");
            Class_Name.setText("");
            jComboBox1.setSelectedItem("00");
            Lecture_Name.setText("");
            Time_In.setText("");
            Time_Out.setText("");
             Schedule.setText("");
             
            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
             Class_IDs.setText("");
            Class_Name.setText("");
            jComboBox1.setSelectedItem("00");
            Lecture_Name.setText("");
            Time_In.setText("");
            Time_Out.setText("");
             Schedule.setText("");
        } else {
           Class_IDs.setText("");
            Class_Name.setText("");
            jComboBox1.setSelectedItem("00");
            Lecture_Name.setText("");
            Time_In.setText("");
            Time_Out.setText("");
             Schedule.setText("");
            ;
        }        // TODO add you
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
              DefaultTableModel ClassDe  = (DefaultTableModel )jTable1.getModel();
   Class_IDs.setText(ClassDe.getValueAt(jTable1.getSelectedRow(),0).toString());
    Class_Name.setText(ClassDe.getValueAt(jTable1.getSelectedRow(),1).toString());
     jComboBox1.setSelectedItem(ClassDe.getValueAt(jTable1.getSelectedRow(),2).toString());                        
   Lecture_Name.setText(ClassDe.getValueAt(jTable1.getSelectedRow(),3).toString());
    Time_In.setText(ClassDe.getValueAt(jTable1.getSelectedRow(),4).toString());
     Time_Out.setText(ClassDe.getValueAt(jTable1.getSelectedRow(),5).toString());
       Schedule.setText(ClassDe.getValueAt(jTable1.getSelectedRow(),6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       loadCourseTable();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Class_IDs;
    private javax.swing.JTextField Class_Name;
    private javax.swing.JTextField Lecture_Name;
    private javax.swing.JTextField Schedule;
    private javax.swing.JTextField Time_In;
    private javax.swing.JTextField Time_Out;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
