/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CourseUI.java
 *
 * Created on Feb 6, 2016, 12:33:18 PM
 */
package UIDesigns;

import Method.Course;
import Method.CourseDetails;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ESOFT
 */
public class CourseUI extends javax.swing.JFrame {
    
    private Vector<Vector<String>> data; //Used for data from database
    private Vector<String> header;
    private Vector<String> couse;
    private Vector<Vector<String>>courseydata; 
    /** Creates new form CourseUI */


    public CourseUI() {
        initComponents();
         header = new Vector<String>();
        header.add("Code");
        header.add("Name");
        loadCourseTable();
    ;
    }
 private void loadCourseTable() {

        CourseDetails dao = new CourseDetails();
        data = dao.getCourseDetails();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
        jScrollPane1.setViewportView(jTable1);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        codetxt = new javax.swing.JTextField();
        csnametxt = new javax.swing.JTextField();
        CourserIdtxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("AlpenhornSSK", 1, 18)); // NOI18N
        jLabel1.setText("Course Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Course Code: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Course Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        codetxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(codetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 186, 28));

        csnametxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(csnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 184, 30));

        CourserIdtxt.setBackground(new java.awt.Color(204, 204, 255));
        CourserIdtxt.setForeground(new java.awt.Color(102, 102, 102));
        CourserIdtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourserIdtxtActionPerformed(evt);
            }
        });
        getContentPane().add(CourserIdtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 130, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Nmae"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane2.setViewportView(jScrollPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 460, 250));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home-PC\\Documents\\StudentRegSystem\\src\\Image\\1460830381_Save.ico")); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home-PC\\Documents\\StudentRegSystem\\src\\Image\\Apps-system-software-update-icon.png")); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        Search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search-icon.png"))); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete-icon.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Refresh-icon.png"))); // NOI18N
        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/go-back-icon.png"))); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabel4.setBackground(new java.awt.Color(153, 255, 153));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 290));

        setSize(new java.awt.Dimension(994, 327));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String code = codetxt.getText();
        String cname = csnametxt.getText();
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Save This Recode?");

        if (x == 0) {
            Course cs = new Course(code,cname);

            CourseDetails dao = new CourseDetails();
            dao. addCourse(cs);
            codetxt.setText("");
            csnametxt.setText("");


            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
            codetxt.setText("");
            csnametxt.setText("");
        } else {
            codetxt.setText("");
            csnametxt.setText("");
            ;
        }



    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         new AdminHomeUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String code = codetxt.getText();
        String cname = csnametxt.getText();
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Change This Recode?");

        if (x == 0) {
            /* EmployeeDetails em;
            em = new EmployeeDetails(emppid, lname, con1, con2, address, des);

            dao.updateEmployee(em);
             *
             *
             *
             */
            Course cs = new Course(code,cname);

            CourseDetails dao = new CourseDetails();
            dao.updateCourse(cs);
            codetxt.setText("");
            csnametxt.setText("");


            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
            codetxt.setText("");
            csnametxt.setText("");
        } else {
            codetxt.setText("");
            csnametxt.setText("");
            ;
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String code = codetxt.getText();
        String cname = csnametxt.getText();
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Delete This Recode?");

        if (x == 0) {
            /* EmployeeDetails em;
            em = new EmployeeDetails(emppid, lname, con1, con2, address, des);

            dao.updateEmployee(em);
             *
             *
             *
             */
            Course cs = new Course(code,cname);

            CourseDetails dao = new CourseDetails();
            dao.deleteBrand(cs);
            codetxt.setText("");
             csnametxt.setText("");


            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Delete Surccefull");

        } else if (x == 1) {
            codetxt.setText("");
             csnametxt.setText("");
        } else {
            codetxt.setText("");
           csnametxt.setText("");
            ;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CourserIdtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourserIdtxtActionPerformed
        // TODO add your handling code here:
     
      
    }//GEN-LAST:event_CourserIdtxtActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        codetxt.setText("");
        csnametxt.setText("");
     
    }//GEN-LAST:event_jButton5ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
           String Id = CourserIdtxt.getText();
        int supid = Integer.valueOf(Id);

       CourseDetails dao = new CourseDetails();
       Course sp = dao.searchDetails(Id);

        /* brandnametxt.setText(d.getName());
         suppIDbrandcmb.setSelectedItem(d.getSupplierId());
         supbrandNametxt.setText(d.getSupplierName());
         branddescriptiontxt.setText(d.getDescription());*/
      
        codetxt.setText(sp.getCode());
        csnametxt.setText(sp.getName());
    }//GEN-LAST:event_SearchActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         loadcourseTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel Student  = (DefaultTableModel )jTable1.getModel();
   codetxt.setText(Student.getValueAt(jTable1.getSelectedRow(),0).toString());
   csnametxt.setText(Student.getValueAt(jTable1.getSelectedRow(),1).toString());     

    }//GEN-LAST:event_jTable1MouseClicked
 private void loadcourseTable() {

        couse= new Vector<String>();
        couse.add("Code");
        couse.add("Name");
   
        CourseDetails dao = new CourseDetails();
       courseydata = dao.getCourseDetails();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(courseydata, couse));
        jScrollPane1.setViewportView(jTable1);
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CourseUI().setVisible(true);
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CourserIdtxt;
    private javax.swing.JButton Search;
    private javax.swing.JTextField codetxt;
    private javax.swing.JTextField csnametxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
