/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIDesigns;
import Method.ModuleDetails;
import java.util.ArrayList;
import Method.LeacherDetails;
import Method.DdDetails;
import Method.Detailsdata;
import java.util.Iterator;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.awt.Component;
import Method.Simodeldetails;
import Method.StudentDetails;

/**
 *
 * @author Home-PC
 */
public class Details extends javax.swing.JPanel {
   private Vector<Vector<String>> data; //Used for data from database
    private Vector<String> header;
    private Vector<String> headers;
    private Vector<String> Module;
    private Component rootPane;
    /**
     * Creates new form Details
     */
    public Details() {
  
         initComponents();
          fillModuleName();
           fillModuleName2();
           fillStudentdetails(); 
          fillLeacherName();
        
        header = new Vector<String>();
        header.add("lec_id");
        header.add("mod_num");
        headers = new Vector<String>();
        headers.add("sid");
        headers.add("mod_num");
              loadDetailaTable();
         
 loadDetailaTables();
      ;  
    }
    
     private void loadDetailaTable() {

        Detailsdata dao = new Detailsdata();
        data = dao.getLecDetails();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
          jScrollPane2.setViewportView(jTable2);
     }
     private void loadDetailaTables() {

        Detailsdata dao = new Detailsdata();
        data = dao.getst_moDetails();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                data, headers));
          jScrollPane1.setViewportView(jTable1);
     }
      private void fillModuleName() {
      ModuleDetails dao = new ModuleDetails();
        ArrayList ModuleList = dao.getModule();

        Iterator i = ModuleList.iterator();

        while (i.hasNext()) {
            jComboBox2.addItem(i.next());

        }

        String csModule = jComboBox2.getSelectedItem().toString();
        jScrollPane1.setViewportView(jTable1);

    }
        private void fillModuleName2() {
      ModuleDetails dao = new ModuleDetails();
        ArrayList ModuleList = dao.getModule();

        Iterator i = ModuleList.iterator();

        while (i.hasNext()) {
            model.addItem(i.next());

        }

        String csModule = model.getSelectedItem().toString();
        jScrollPane1.setViewportView(jTable1);

    }
          private void fillStudentdetails() {
      StudentDetails dao = new StudentDetails();
        ArrayList StudentList = dao.getStudent();

        Iterator i = StudentList.iterator();

        while (i.hasNext()) {
            jsidcombotxt.addItem(i.next());

        }

        String csstudent = jsidcombotxt.getSelectedItem().toString();
        jScrollPane1.setViewportView(jTable1);

    }
   private void fillLeacherName() {

       LeacherDetails daos = new LeacherDetails();
        ArrayList LeacherList= daos. getLeacher ();
        
        Iterator i = LeacherList.iterator();
   
        while (i.hasNext()) {
            jComboBox1.addItem(i.next());
            
   
        }
      String csLeacher = jComboBox1.getSelectedItem().toString();
        jScrollPane1.setViewportView(jTable1);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        model = new javax.swing.JComboBox();
        jsidcombotxt = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1090, 660));

        jTabbedPane3.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));
        jTabbedPane3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane3.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jTabbedPane3.setMinimumSize(new java.awt.Dimension(400, 54));
        jTabbedPane3.setOpaque(true);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(1090, 660));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel12.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 193, 980, 410));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1463780845_hammer_screwdriver.png"))); // NOI18N
        jButton1.setText("Active");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 130, 70));

        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 370, 29));

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 370, 32));

        jPanel12.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 980, 120));

        jTabbedPane3.addTab("lec_conduct_module", jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 255, 51));
        jScrollPane1.setViewportView(jTable1);

        jPanel13.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 660, 570));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1463780845_hammer_screwdriver.png"))); // NOI18N
        jButton2.setText("Active");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsidcombotxt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(model, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jsidcombotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 280, 140));

        jTabbedPane3.addTab("                    Student_follows_Modules                       ", jPanel13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1199, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
         try {
            DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
            int i = jTable2.getSelectedRow();

            String lec_id = dtm.getValueAt(i, 0).toString();
             jComboBox1.setSelectedItem(lec_id);

            
            String mod_num = dtm.getValueAt(i, 1).toString();
             jComboBox1.setSelectedItem(mod_num);

        } catch (Exception e) {
            e.printStackTrace();
        }
                                        

    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String lec_id = jComboBox1.getSelectedItem().toString();
        int lec_id1= Integer.valueOf(lec_id);
         String mod_num = jComboBox2.getSelectedItem().toString();
      int mod_nums= Integer.valueOf(mod_num);
         int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Save This Recode?");

        if (x == 0) {
           DdDetails cs = new DdDetails(lec_id1,mod_nums);
           
            Detailsdata dao = new Detailsdata();
            dao. addLecmod(cs);
           jComboBox2.setSelectedItem("");
            jComboBox1.setSelectedItem("");
            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
           jComboBox2.setSelectedItem("");
            jComboBox1.setSelectedItem("");
        } else {
          jComboBox2.setSelectedItem("");
            jComboBox1.setSelectedItem("");
            ;
        }
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String sid = jsidcombotxt.getSelectedItem().toString();
        int sids= Integer.valueOf(sid);
         String mod_num = model.getSelectedItem().toString();
      int mod_nums= Integer.valueOf(mod_num);
         int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Save This Recode?");

        if (x == 0) {
           Simodeldetails cs = new Simodeldetails(sids,mod_nums);
           
            Detailsdata dao = new Detailsdata();
            dao. addslLecmod(cs);
           jsidcombotxt.setSelectedItem("");
             model.setSelectedItem("");
            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
           jsidcombotxt.setSelectedItem("");
             model.setSelectedItem("");
        } else {
           jsidcombotxt.setSelectedItem("");
           model.setSelectedItem("");
            ;
        }
 
                             
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JComboBox jsidcombotxt;
    private javax.swing.JComboBox model;
    // End of variables declaration//GEN-END:variables
}
