/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIDesigns;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.awt.Color;
import UIDesigns.Modulesde;
 import UIDesigns.StudentRagistration1;
import UIDesigns.Leacherform;
import UIDesigns.Details;


/**
 *
 * @author Home
 */
public class HomeUI extends javax.swing.JFrame {
  private Color color;
  private Modulesde Module;
  private StudentRagistration1 StudentRagistration1; 
  private View_Grades View_Grades;
   private Details Details;
   private StudentGrade Grade;
   private ClassDe Class;
     private Class_view Class_view;
     private Studentpayment Payment;
private  Attendance Attendance;
    /**
     * Creates new form AdminHomeUI
     */
    public HomeUI() {
        initComponents();
        showDate();
        color = new Color(0, 153, 51);
      
    }

    HomeUI(String uname) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
       void showDate(){
       Date d =  new Date();
       SimpleDateFormat sdf = new SimpleDateFormat("EEEE,dd/MM/yyyy hh:mm:ss a");
       jLabel6.setText(sdf.format(d));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Register = new javax.swing.JButton();
        Course = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        module = new javax.swing.JButton();
        Leachetb = new javax.swing.JButton();
        Leachetb1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Leachetb2 = new javax.swing.JButton();
        Leachetb3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Admin"));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        Register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/document_new.png"))); // NOI18N
        Register.setText("Register");
        Register.setPreferredSize(new java.awt.Dimension(137, 59));
        Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterMouseExited(evt);
            }
        });
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        Course.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Course.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Teacher-icon.png"))); // NOI18N
        Course.setText("Time Table");
        Course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CourseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CourseMouseExited(evt);
            }
        });
        Course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Test-paper-512.png"))); // NOI18N
        jButton1.setText("View Marks");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        module.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        module.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Paste.png"))); // NOI18N
        module.setText("Module ");
        module.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                moduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                moduleMouseExited(evt);
            }
        });
        module.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moduleActionPerformed(evt);
            }
        });

        Leachetb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Leachetb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/1463851511_control-center2.png"))); // NOI18N
        Leachetb.setText("Active");
        Leachetb.setEnabled(false);
        Leachetb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LeachetbMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LeachetbMouseExited(evt);
            }
        });
        Leachetb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeachetbActionPerformed(evt);
            }
        });

        Leachetb1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Leachetb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Balance.png"))); // NOI18N
        Leachetb1.setText("Report");
        Leachetb1.setEnabled(false);
        Leachetb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Leachetb1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Leachetb1MouseExited(evt);
            }
        });
        Leachetb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Leachetb1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Test-paper-512.png"))); // NOI18N
        jButton3.setText("Grades");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/classes-icon-8.png"))); // NOI18N
        jButton4.setText("Class");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Leachetb2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Leachetb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cash.png"))); // NOI18N
        Leachetb2.setText("Payments");
        Leachetb2.setEnabled(false);
        Leachetb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Leachetb2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Leachetb2MouseExited(evt);
            }
        });
        Leachetb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Leachetb2ActionPerformed(evt);
            }
        });

        Leachetb3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Leachetb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/attandance.png"))); // NOI18N
        Leachetb3.setText("Attendance");
        Leachetb3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Leachetb3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Leachetb3MouseExited(evt);
            }
        });
        Leachetb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Leachetb3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Course, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(module, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Leachetb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Leachetb1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Leachetb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Leachetb3, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(Register, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Course, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(module, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Leachetb2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Leachetb3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Leachetb, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Leachetb1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, 660));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/student icon.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 118, 58));

        jButton2.setBackground(new java.awt.Color(0, 153, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lllllllllllllllllllll.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 73, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 358, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Management System");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 358, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 70));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home-PC\\Documents\\StudentRegSystem\\src\\Image\\students.jpg")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel4.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 1090, 660));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1322, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 731, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1322, 731));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (Class == null) {
            Class = new ClassDe();
        }

        jPanel4.removeAll();
        jPanel4.add(Class);
        jPanel4.revalidate();
        jPanel4.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
        jButton4.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
        jButton4.setBackground(color);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (Grade == null) {
            Grade = new StudentGrade();
        }

        jPanel4.removeAll();
        jPanel4.add(Grade);
        jPanel4.revalidate();
        jPanel4.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
        jButton3.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
        jButton3.setBackground(color);
    }//GEN-LAST:event_jButton3MouseEntered

    private void Leachetb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Leachetb1ActionPerformed
        // TODO add your handling code here:
        new Reports().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Leachetb1ActionPerformed

    private void Leachetb1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leachetb1MouseExited
        // TODO add your handling code here:
        Leachetb1.setBackground(Color.WHITE);
    }//GEN-LAST:event_Leachetb1MouseExited

    private void Leachetb1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leachetb1MouseEntered
        // TODO add your handling code here:
        Leachetb1.setBackground(color);
    }//GEN-LAST:event_Leachetb1MouseEntered

    private void LeachetbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeachetbActionPerformed
        // TODO add your handling code here:
        if (Details == null) {
            Details = new Details();
        }

        jPanel4.removeAll();
        jPanel4.add(Details);
        jPanel4.revalidate();
        jPanel4.repaint();
    }//GEN-LAST:event_LeachetbActionPerformed

    private void LeachetbMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeachetbMouseExited
        // TODO add your handling code here:
        Leachetb.setBackground(Color.WHITE);
    }//GEN-LAST:event_LeachetbMouseExited

    private void LeachetbMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeachetbMouseEntered
        // TODO add your handling code here:
        Leachetb.setBackground(color);
    }//GEN-LAST:event_LeachetbMouseEntered

    private void moduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moduleActionPerformed
        // TODO add your handling code here:
        if (Module == null) {
            Module = new Modulesde();
        }

        jPanel4.removeAll();
        jPanel4.add(Module);
        jPanel4.revalidate();
        jPanel4.repaint();

    }//GEN-LAST:event_moduleActionPerformed

    private void moduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moduleMouseExited
        // TODO add your handling code here:
        module.setBackground(Color.WHITE);
    }//GEN-LAST:event_moduleMouseExited

    private void moduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moduleMouseEntered
        // TODO add your handling code here:
        module.setBackground(color);
    }//GEN-LAST:event_moduleMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (View_Grades == null) {
            View_Grades = new View_Grades();
        }

        jPanel4.removeAll();
        jPanel4.add(View_Grades);
        jPanel4.revalidate();
        jPanel4.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
        jButton1.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jButton1.setBackground(color);
    }//GEN-LAST:event_jButton1MouseEntered

    private void CourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseActionPerformed
        
 if (Class_view == null) {
            Class_view = new Class_view();
        }

        jPanel4.removeAll();
        jPanel4.add(Class_view);
        jPanel4.revalidate();
        jPanel4.repaint();
                                            

        // TODO add your handling code here:
    }//GEN-LAST:event_CourseActionPerformed

    private void CourseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseMouseExited
        // TODO add your handling code here:
        Course.setBackground(Color.WHITE);
    }//GEN-LAST:event_CourseMouseExited

    private void CourseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseMouseEntered
        // TODO add your handling code here:
        Course.setBackground(color);
    }//GEN-LAST:event_CourseMouseEntered

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed

        if (StudentRagistration1 == null) {
            StudentRagistration1 = new StudentRagistration1();
        }

        jPanel4.removeAll();
        jPanel4.add(StudentRagistration1);
        jPanel4.revalidate();
        jPanel4.repaint();

        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterActionPerformed

    private void RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseExited
        // TODO add your handling code here:
        Register.setBackground(Color.WHITE);
    }//GEN-LAST:event_RegisterMouseExited

    private void RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterMouseEntered
        // TODO add your handling code here:
        Register.setBackground(color);

    }//GEN-LAST:event_RegisterMouseEntered

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Leachetb2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leachetb2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Leachetb2MouseEntered

    private void Leachetb2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leachetb2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Leachetb2MouseExited

    private void Leachetb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Leachetb2ActionPerformed
        // TODO add your handling code here:
          if (Payment == null) {
            Payment = new Studentpayment();
        }

        jPanel4.removeAll();
        jPanel4.add(Payment);
        jPanel4.revalidate();
        jPanel4.repaint();
    }//GEN-LAST:event_Leachetb2ActionPerformed

    private void Leachetb3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leachetb3MouseEntered
        // TODO add your handling code here:
          Leachetb3.setBackground(color);
    }//GEN-LAST:event_Leachetb3MouseEntered

    private void Leachetb3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Leachetb3MouseExited
        // TODO add your handling code here:
             Leachetb3.setBackground(Color.WHITE);
    }//GEN-LAST:event_Leachetb3MouseExited

    private void Leachetb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Leachetb3ActionPerformed
        // TODO add your handling code here:
            if (Attendance == null) {
            Attendance = new Attendance();
        }

        jPanel4.removeAll();
        jPanel4.add(Attendance);
        jPanel4.revalidate();
        jPanel4.repaint();
        
    }//GEN-LAST:event_Leachetb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Course;
    private javax.swing.JButton Leachetb;
    private javax.swing.JButton Leachetb1;
    private javax.swing.JButton Leachetb2;
    private javax.swing.JButton Leachetb3;
    private javax.swing.JButton Register;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton module;
    // End of variables declaration//GEN-END:variables
}
