/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIDesigns;

import Method.Lectures;
import Method.LeacherDetails;
import javax.swing.JOptionPane;
import java.awt.Component;
import javax.swing.table.DefaultTableModel;
import java.util.Vector;

/**
 *
 * @author Home-PC
 */
public class Leacherform extends javax.swing.JPanel {
  private Component rootPane;
  private Vector<Vector<String>> data; //Used for data from database
    private Vector<String> header;
    private Vector<String> Module;
      private Vector<Vector<String>>courseydata; 
    /**
     * Creates new form Leacherform
     */
    public Leacherform() {
        initComponents(); header = new Vector<String>();
        header.add("lec_id");
        header.add("fname");
        header.add("lname");
        header.add("DOB"); 
        loadModulesTable();
        
    }
 private void loadModulesTable() {

        LeacherDetails dao = new LeacherDetails();
        data = dao.getLeacherDetails();

       Leacher.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lec_id = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DOB = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Leacher = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lname1 = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(1313, 470));
        setPreferredSize(new java.awt.Dimension(1313, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(lec_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 210, 30));
        add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 210, 30));
        add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 210, 30));

        jLabel3.setText("DOB");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 30, 30));

        jLabel4.setText("Learcher Id");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 70, 30));
        add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 210, 30));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 80, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete-icon.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Apps-system-software-update-icon.png"))); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 90, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Refresh-icon.png"))); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        jLabel5.setText("Fist Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 70, 30));

        Leacher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Leacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LeacherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Leacher);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 1030, 260));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home-PC\\Documents\\StudentRegSystem\\src\\Image\\1463780845_hammer_screwdriver.png")); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 90, -1));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setAutoscrolls(true);
        jLabel7.setOpaque(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 1030, 100));

        jLabel6.setText("Last Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 70, 30));

        jLabel2.setBackground(new java.awt.Color(0, 153, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Leacher Details");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1090, 70));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setMaximumSize(new java.awt.Dimension(1090, 1090));
        jLabel1.setMinimumSize(new java.awt.Dimension(660, 660));
        jLabel1.setName(""); // NOI18N
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 660));

        jLabel8.setText("Last Name");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 70, 30));
        add(lname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 210, 30));

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String lec_ids = lec_id.getText();
          int lec_id1= Integer.valueOf(lec_ids);
        String cname = fname.getText();
        String lnames = lname.getText();
        String DOBs = DOB.getText();
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Save This Recode?");

        if (x == 0) {
            Lectures cs = new Lectures(lec_id1,cname,lnames,DOBs);

            LeacherDetails dao = new LeacherDetails();
            dao. addLeacher(cs);
        lec_id.setText("");
          fname.setText("");
        lname.setText("");
       DOB.setText("");
     


            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
            lec_id.setText("");
          fname.setText("");
        lname.setText("");
       DOB.setText("");
        } else {
            lec_id.setText("");
          fname.setText("");
        lname.setText("");
       DOB.setText("");;
            ;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      String lec_ids = lec_id.getText();
          int lec_id1= Integer.valueOf(lec_ids);
        String cname = fname.getText();
        String lnames = lname.getText();
        String DOBs = DOB.getText();

        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Delete This Recode?");

        if (x == 0) {
            /* EmployeeDetails em;
            em = new EmployeeDetails(emppid, lname, con1, con2, address, des);

            dao.updateEmployee(em);
            *
            *
            *
            */
           Lectures cs = new Lectures(lec_id1,cname,lnames,DOBs);

             LeacherDetails dao = new LeacherDetails();
            dao. addLeacher(cs);
        lec_id.setText("");
          fname.setText("");
        lname.setText("");
       DOB.setText("");
     

            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Delete Surccefull");

        } else if (x == 1) {
              lec_id.setText("");
          fname.setText("");
        lname.setText("");
       DOB.setText("");
        } else {
              lec_id.setText("");
          fname.setText("");
        lname.setText("");
       DOB.setText("");

        }   ;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
          lec_id.setText("");
          fname.setText("");
        lname.setText("");
       DOB.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        loadlechTable(); 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void LeacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeacherMouseClicked
        // TODO add your handling code here:
  DefaultTableModel LeacherForm  = (DefaultTableModel )Leacher.getModel();
   lec_id.setText(LeacherForm.getValueAt(Leacher.getSelectedRow(),0).toString());
    fname.setText(LeacherForm.getValueAt(Leacher.getSelectedRow(),1).toString());
     lname.setText(LeacherForm.getValueAt(Leacher.getSelectedRow(),2).toString());
     DOB.setText(LeacherForm.getValueAt(Leacher.getSelectedRow(),3).toString());
    }//GEN-LAST:event_LeacherMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       String lec_ids = lec_id.getText();
          int lec_id1= Integer.valueOf(lec_ids);
        String fnames = fname.getText();
        String lnames =lname.getText();
        String DOBs= DOB.getText();
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Change This Recode?");

        if (x == 0) {
            /* EmployeeDetails em;
            em = new EmployeeDetails(emppid, lname, con1, con2, address, des);

            dao.updateEmployee(em);
             *
             *
             *
             */
            Lectures cs = new Lectures(lec_id1,fnames,lnames,DOBs);

            LeacherDetails dao = new LeacherDetails();
            dao.updateLeacher(cs);
             lec_id.setText("");
          fname.setText("");
        lname.setText("");
       DOB.setText("");


            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
             lec_id.setText("");
          fname.setText("");
        lname.setText("");
       DOB.setText("");
       
        } else {
            lec_id.setText("");
          fname.setText("");
        lname.setText("");
       DOB.setText("");
       
            ;
        }

    }//GEN-LAST:event_jButton5ActionPerformed
 private void loadlechTable() {

        header= new Vector<String>();
        header.add("lec_id");
        header.add("fname");
        header.add("lname");
        header.add("DOB"); 
        LeacherDetails dao = new LeacherDetails();
       courseydata = dao.getLeacherDetails();

        Leacher.setModel(new javax.swing.table.DefaultTableModel(courseydata, header));
        jScrollPane1.setViewportView(Leacher);
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DOB;
    private javax.swing.JTable Leacher;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lec_id;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField lname1;
    // End of variables declaration//GEN-END:variables
}
