/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIDesigns;

import Method.User;
import Method.UserDetails;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import Data.DBConnManager;
import SMS.ModamSMS;
import static SMS.ModamSMS.kk;
import static UIDesigns.sms.date;
import static UIDesigns.sms.jProgressBar1;
import static UIDesigns.sms.mobile;
import static UIDesigns.sms.timel;
import bsh.ParserConstants;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;


/**
 *
 * @author Home-PC
 */
public class Login extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    int count = 1;

    /**
     * Creates new form User
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, 10));

        jToggleButton1.setText("Password Reset");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 130, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 102));
        jButton1.setText("Submit");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordKeyReleased(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, 30));

        jButton2.setBackground(new java.awt.Color(255, 153, 102));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/loginl.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, 90));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT--", "Student", "Admin" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 140, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-1.png"))); // NOI18N
        jLabel1.setText("Admin");
        jLabel1.setFocusCycleRoot(true);
        jLabel1.setFocusTraversalPolicyProvider(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: try{
//        String sql = "Select usertype from login where UserName=? and PassWord=? and usertype=?";
//        try {
//
//            con = DriverManager.getConnection("jdbc:sqlserver://HOME;databaseName=Student", "NEW_USER", "123");
//            pst = con.prepareStatement(sql);
//            pst.setString(1, username.getText());
//            pst.setString(2, password.getText());
//            pst.setString(3, jComboBox1.getSelectedItem().toString());
//            rs = pst.executeQuery();
//            if (rs.next()) {
//                if ("Student".equals(rs.getString("usertype"))) {
//                    new studentUI().setVisible(true);
//                    this.setVisible(false);
//                } else if ("Admin".equals(rs.getString("usertype"))) {
//
//                    new AdminHomeUI().setVisible(true);
//                    this.setVisible(false);
//                } else {
//
//                }
//            } else {
//                if (count == 1) {
//                    ++count;
//                    JOptionPane.showMessageDialog(null, "Username and Password Incorrect\nYou have 2 chanse", "Warning", JOptionPane.WARNING_MESSAGE);
//                } else if (count == 2) {
//
//                    ++count;
//                    JOptionPane.showMessageDialog(null, "Username and Password Incorrect\nYou have 1 chanse", "Warning", JOptionPane.WARNING_MESSAGE);
//
//                } else if (count == 3) {
//
//                    ++count;
//                    new Thread(new Runnable() {
//
//                        @Override
//                        public void run() {
//                            try {
//                                jLabel4.setText("Checking Please wait");
//                                send_sms(username.getText());
//
//                            } catch (Exception ex) {
////                        clickcount1 = 0;
////                        jButton2.setEnabled(true);
////                        jButton3.setEnabled(true);
//                                JOptionPane.showMessageDialog(null, "Message Not Send to" + username, "Warning", JOptionPane.ERROR_MESSAGE);
////                        JOptionPane.showMessageDialog(null, ex + " Error happen");
////                        StringWriter sw = new StringWriter();
////                        ex.printStackTrace(new PrintWriter(sw));
////
////                        writfile(sw.toString());
////                        jProgressBar1.setVisible(false);
//
//                                ex.printStackTrace();
//
//                            }
//                        }
//
//                        //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//                    }).start();
//
//                    JOptionPane.showMessageDialog(null, "Username and Password Incorrect\nSystem Will exit now sorry", "Warning", JOptionPane.WARNING_MESSAGE);
//
//                }
//
//                //  jLabel4.setText("Username and Password Incorrect");
//            }
//        } catch (Exception e) {
//
//        }
          try {
         String uname = username.getText();
        String pwd = password.getText();

        UserDetails dao = new UserDetails();
        User emp = dao.login(uname, pwd);

        if ("Student".equals(emp.getusertype())) {

          
                    new HomeUI().setVisible(true);
                    this.setVisible(false);
            
                
        } else if ("Admin".equals(emp.getusertype())) {

               new AdminHomeUI().setVisible(true);
                    this.setVisible(false);
      
            } else {
                if (count == 1) {
                    ++count;
                    JOptionPane.showMessageDialog(null, "Username and Password Incorrect\nYou have 2 chanse", "Warning", JOptionPane.WARNING_MESSAGE);
                } else if (count == 2) {

                    ++count;
                    JOptionPane.showMessageDialog(null, "Username and Password Incorrect\nYou have 1 chanse", "Warning", JOptionPane.WARNING_MESSAGE);

                } else if (count == 3) {

                    ++count;
                    new Thread(new Runnable() {

                        @Override
                        public void run() {
                            try {
                                jLabel4.setText("Checking Please wait");
                                send_sms(username.getText());

                            } catch (Exception ex) {
//                        clickcount1 = 0;
//                        jButton2.setEnabled(true);
//                        jButton3.setEnabled(true);
                                JOptionPane.showMessageDialog(null, "Message Not Send to" + username, "Warning", JOptionPane.ERROR_MESSAGE);
//                        JOptionPane.showMessageDialog(null, ex + " Error happen");
//                        StringWriter sw = new StringWriter();
//                        ex.printStackTrace(new PrintWriter(sw));
//
//                        writfile(sw.toString());
//                        jProgressBar1.setVisible(false);

                                ex.printStackTrace();

                            }
                        }

                        //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                    }).start();

                    JOptionPane.showMessageDialog(null, "Username and Password Incorrect\nSystem Will exit now sorry", "Warning", JOptionPane.WARNING_MESSAGE);

                }

//                  jLabel4.setText("Incorrect Username Or Password");
            }
        } catch (Exception e) {

    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
        jButton1.doClick();
    }//GEN-LAST:event_passwordActionPerformed

    private void passwordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyReleased
        // TODO add your handling code here:
        if (username.getText().isEmpty() || new String(password.getPassword()).isEmpty()) {
            jButton1.setEnabled(false);
        } else {
            jButton1.setEnabled(true);
        }

    }//GEN-LAST:event_passwordKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here: new AdminHomeUI().setVisible(true);
        new PasswordResetUI().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    private void send_sms(String name) {
        ModamSMS app = new ModamSMS("COM18");
        String body = "Try unauthorized access check your system";
        body += "\n -- Student Management System --";
        app.sendMessage("0757667568", body);

        if (kk) {
            // jProgressBar1.setVisible(false);

            System.exit(0);
                                  //  jProgressBar1.setString(" Send Success To " + mobile);

                                    //JOptionPane.showMessageDialog(null, jTextField1.getText() + " " + "Send Success", "SMS INFO", JOptionPane.INFORMATION_MESSAGE);
        } else {
            System.exit(0);
            //  JOptionPane.showMessageDialog(null, "Messege Not Sent Trying Faild, Please Resend", "SMS INFO", JOptionPane.ERROR_MESSAGE);
        }

        //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
