/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIDesigns;


import Method.Course;
import Method.ModuleDetails;
import Method.Module;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Vector;
import java.util.Iterator;
import Method.CourseDetails;
import java.awt.Component;


import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Home-PC
 */
public class Modulesde1 extends javax.swing.JPanel {
private Vector<Vector<String>> data; //Used for data from database
    private Vector<String> header;
    private Vector<String> Module;
    private Component rootPane;
    
    /**
     * Creates new form Module
     */
    public Modulesde1() {
        initComponents();
        fillCoursecode();
        fillCourseNames();
        header = new Vector<String>();
        header.add("mod_num");
        header.add("Name");
        header.add("num_of_units");
          header.add("course");
            header.add("course");
       loadModulesTable();
    }
    
 private void loadModulesTable() {

        ModuleDetails dao = new ModuleDetails();
        data = dao.getModuleDetails();

        ModuleTable.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
      
    }
private void fillCoursecode() {
        CourseDetails dao = new CourseDetails();
        ArrayList codeList = dao.getCourse();

        Iterator i = codeList.iterator();

        while (i.hasNext()) {
            jComboBox1.addItem(i.next());
        }

        String cscode = jComboBox1.getSelectedItem().toString();
}
 private void fillCourseNames() {
       CourseDetails dao = new CourseDetails();
        ArrayList NameList = dao.getCourseName();

        Iterator i = NameList.iterator();

        while (i.hasNext()) {
            jComboBox2.addItem(i.next());
        }

        String csName = jComboBox2.getSelectedItem().toString();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        txtnum_of_units = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtmod_num = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ModuleTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(780, 470));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Module No");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 230, 30));
        add(txtnum_of_units, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 230, 30));

        jLabel6.setText("Course No");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 230, 30));

        jLabel4.setText("Module Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, 30));
        add(txtmod_num, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 230, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home-PC\\Documents\\StudentRegSystem\\src\\Image\\1460830381_Save.ico")); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete-icon.png"))); // NOI18N
        Delete.setText("Delete");
        Delete.setEnabled(false);
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, -1));

        Cancel.setText("Clear");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 80, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Temparey Delete Table Rows ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 210, 30));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, 30));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Refresh-icon.png"))); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 50, 100, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 350, 140));

        ModuleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ModuleTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModuleTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(ModuleTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 960, 210));

        jLabel5.setText("Num_of_Units");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, 30));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 230, 30));

        jLabel7.setText("Course Name");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 153, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Module Details");
        jLabel2.setOpaque(true);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 1040, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel mod;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mod_num  = txtmod_num.getText();
        int mod_num1 = Integer.valueOf(mod_num);
        String name = txtname.getText();
        String num_of_units = txtnum_of_units.getText();
        int num_of_unit1 = Integer.valueOf(num_of_units);
        String code = jComboBox1.getSelectedItem().toString();
        String course = jComboBox2.getSelectedItem().toString();
         int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Save This Recode?");

        if (x == 0) {
           Module cs = new Module(mod_num1,name,num_of_unit1,code,course);

            ModuleDetails dao = new ModuleDetails();
            dao. addModule(cs);
            txtmod_num.setText("");
            txtname.setText("");
            txtnum_of_units.setText("");
            jComboBox1.setSelectedItem("00");
             jComboBox2.setSelectedItem("00");
            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
            txtmod_num.setText("");
            txtname.setText("");
            txtnum_of_units.setText("");
            jComboBox1.setSelectedItem("");
             jComboBox2.setSelectedItem("");
        } else {
             txtmod_num.setText("");
            txtname.setText("");
            txtnum_of_units.setText("");
            jComboBox1.setSelectedItem("");
                jComboBox2.setSelectedItem("");
            ;
        }
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
 
        String mod_num  = txtmod_num.getText();
        int mod_num1 = Integer.valueOf(mod_num);
        String name = txtname.getText();
        String num_of_units = txtnum_of_units.getText();
        int num_of_unit1 = Integer.valueOf(num_of_units);
        String code = jComboBox1.getSelectedItem().toString();
           String course = jComboBox2.getSelectedItem().toString();
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Delete This Recode?");

        if (x == 0) {
            /* EmployeeDetails em;
            em = new EmployeeDetails(emppid, lname, con1, con2, address, des);

            dao.updateEmployee(em);
            *
            *
            *
            */
            Module cs = new Module(mod_num1,name,num_of_unit1,code,course);

            ModuleDetails dao = new ModuleDetails();
            dao.deleteBrand(cs);
            txtmod_num.setText("");
            txtname.setText("");
            txtnum_of_units.setText("");
            jComboBox1.setSelectedItem("00");
                jComboBox2.setSelectedItem("00");

            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Delete Surccefull");

        } else if (x == 1) {
            txtmod_num.setText("");
            txtname.setText("");
            txtnum_of_units.setText("");
            jComboBox1.setSelectedItem("");
                jComboBox2.setSelectedItem("");

        } else {
            txtmod_num.setText("");
            txtname.setText("");
            txtnum_of_units.setText("");
            jComboBox1.setSelectedItem("");
                jComboBox2.setSelectedItem("");

        }   ;
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

  DefaultTableModel model  = (DefaultTableModel )ModuleTable.getModel();
int rows = model.getRowCount(); 
for(int i = rows - 1; i >=0; i--)
{
   model.removeRow(0); 
   model.removeRow(1); 
   model.removeRow(2); 
   model.removeRow(3); 
     model.removeRow(4); 
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           String Id = jTextField1.getText();
        int supid = Integer.valueOf(Id);

       ModuleDetails dao = new ModuleDetails();
       Module sp = dao.searchDetails(supid);

        /* brandnametxt.setText(d.getName());
         suppIDbrandcmb.setSelectedItem(d.getSupplierId());
         supbrandNametxt.setText(d.getSupplierName());
         branddescriptiontxt.setText(d.getDescription());*/
      
        txtmod_num.setText(String.valueOf(sp.getmod_num()));
        txtname.setText(sp.getName());
        txtnum_of_units.setText(String.valueOf(sp.getnum_of_units()));
        jComboBox1.setSelectedItem(sp.getcode());
         jComboBox2.setSelectedItem(sp.getcourse());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         loadModulesTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ModuleTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModuleTableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel Model = (DefaultTableModel )ModuleTable.getModel();
   txtmod_num.setText(Model.getValueAt(ModuleTable.getSelectedRow(),0).toString());
   txtname.setText(Model.getValueAt(ModuleTable.getSelectedRow(),1).toString());     
    txtnum_of_units.setText(Model.getValueAt(ModuleTable.getSelectedRow(),2).toString());  
  jComboBox1.setSelectedItem(Model.getValueAt(ModuleTable.getSelectedRow(),3).toString());  
        jComboBox2.setSelectedItem(Model.getValueAt(ModuleTable.getSelectedRow(),4).toString());  
    }//GEN-LAST:event_ModuleTableMouseClicked

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        txtmod_num.setText("");
          txtname.setText("");
             txtnum_of_units.setText("");   
            jComboBox1.setSelectedItem("00");
                 jComboBox2.setSelectedItem("00");
    }//GEN-LAST:event_CancelActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Delete;
    private javax.swing.JTable ModuleTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtmod_num;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnum_of_units;
    // End of variables declaration//GEN-END:variables
}
