/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIDesigns;

import Method.CourseDetails;
import Method.StudentDetails;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import Method.Student;
import Method.Payment;
import Method.PaymentDetails;
import SMS.ModamSMS;
import static SMS.ModamSMS.kk;
import static SMS.ModamSMS.writfile;
import static UIDesigns.sms.get_port;
import static UIDesigns.sms.jProgressBar1;
import static UIDesigns.sms.jTable1;
import static UIDesigns.sms.mobile;
import java.awt.Component;
import java.io.PrintWriter;
import java.io.StringWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.BasicConfigurator;
/**
 *
 * @author Home-PC
 */
public class Studentpayment extends javax.swing.JPanel {
    
    
      int starrowcount = 0;
    int clickcount = 0;

    int clickcount1 = 0;
    public static int c = 0;
    String name = "";
    String owid = "";
    String vno = "";
    String type = "";
    public static String mobile = "";

    String exp = "";

    String documet = "";
    String all = "";

    int no = 0;
    
    
  private Vector<Vector<String>>Paymentydata; 
   private Vector<String> Payment;
     private Vector<Vector<String>>PaymentBalance; 
      private Vector<String> Balance;
       private Vector<String> header;
         private Vector<Vector<String>> data; //Used for data from database
    /**
     * Creates new form Payment
     */
    public Studentpayment() {
        initComponents();
        fillPaymentDetails();
        fillCourseNamess();
    loadPaymentTable();
   loadPaymentBalanceTable();
   loadStudentTables();
    }
private void fillPaymentDetails() {
        PaymentDetails dao = new PaymentDetails();
        ArrayList NameList = dao.getAmountdetails();

        Iterator i = NameList.iterator();

        while (i.hasNext()) {
            jComboBox2.addItem(i.next());
        }

        String csName = jComboBox2.getSelectedItem().toString();

    }
private void fillCourseNamess() {
        StudentDetails dao = new StudentDetails();
        ArrayList NameList = dao.getStudentsdetails();

        Iterator i = NameList.iterator();

        while (i.hasNext()) {
            jComboBox3.addItem(i.next());
        }

        String csName = jComboBox3.getSelectedItem().toString();

    }
  private void loadStudentTables() {
        header = new Vector<String>();
        header.add("sid");
        header.add("fname");
        header.add("phone_num");
      
        StudentDetails dao = new StudentDetails();
        data = dao.getStudentDetailss();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
        jScrollPane3.setViewportView(jTable1);

    }

private void loadPaymentTable() {

        Payment= new Vector<String>();
        Payment.add("StudentName");
        Payment.add("Course");
         Payment.add("Date");
    Payment.add("Amount");
    
        PaymentDetails dao = new PaymentDetails();
       Paymentydata = dao.getPaymentDetails();

        Amount.setModel(new javax.swing.table.DefaultTableModel(Paymentydata, Payment));
        jScrollPane2.setViewportView(Amount);
 }
private void loadPaymentBalanceTable() {

        Balance= new Vector<String>();
Balance.add("BalanceID");
        Balance.add("PId");
         Balance.add("StudentName");
    Balance.add("Course");
      Balance.add("Date");
      Balance.add("Amount");
     Balance.add("Payed");
      Balance.add("Balance");
    
        PaymentDetails dao = new PaymentDetails();
       PaymentBalance = dao.getPaymentBalanceDetails();

        FullPaymentBalance.setModel(new javax.swing.table.DefaultTableModel(PaymentBalance, Balance));
        jScrollPane1.setViewportView(FullPaymentBalance);
 }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dateCombo = new org.freixas.jcalendar.JCalendarCombo();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        FullPaymentBalance = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dateCombo1 = new org.freixas.jcalendar.JCalendarCombo();
        jComboBox3 = new javax.swing.JComboBox();
        Course = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Amount = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        send = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1030, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Student Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setText("Course");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setText("Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        dateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboActionPerformed(evt);
            }
        });
        jPanel1.add(dateCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 540, 40));

        jLabel5.setText("Fees");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jTextField5.setEnabled(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 540, 40));

        jLabel6.setText("Monthly Payment");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 540, 40));

        jLabel7.setText("Balance");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 540, 40));

        FullPaymentBalance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FullPaymentBalance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FullPaymentBalanceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FullPaymentBalance);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 970, 160));

        jButton1.setText("Delete");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 240, 120, 40));

        jButton2.setText("Calculate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 260, 40));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 120, 40));

        jButton4.setText("Reflesh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, 120, 40));

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 540, 37));

        jButton5.setText("Submit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 240, 120, 40));

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 540, 40));

        jTextField9.setEnabled(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 540, 40));

        jTextField10.setEnabled(false);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 540, 40));

        jLabel8.setText("Student ID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jTabbedPane2.addTab("Student Payment", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Date");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        jLabel10.setText("Course Amount");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        jLabel12.setText("Student Name");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        dateCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateCombo1ActionPerformed(evt);
            }
        });
        jPanel2.add(dateCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, 260, 40));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 260, 40));

        Course.setEnabled(false);
        jPanel2.add(Course, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 260, 40));

        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 110, 40));

        jButton7.setText("Submit");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 110, 40));

        Amount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(Amount);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 940, 220));

        jLabel13.setText("Course Name");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 260, 40));

        jTabbedPane2.addTab("Add Payment", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 770, 240));

        send.setText("send");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel3.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        jProgressBar1.setBackground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jProgressBar1.setForeground(new java.awt.Color(255, 0, 102));
        jProgressBar1.setPreferredSize(new java.awt.Dimension(146, 20));
        jProgressBar1.setString("Sending");
        jProgressBar1.setStringPainted(true);
        jPanel3.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 1030, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 770, 90));

        jLabel11.setText("Send Message :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        jTabbedPane2.addTab("SMS Table", jPanel3);

        add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1030, 600));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setAutoscrolls(true);
        jLabel1.setEnabled(false);
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1090, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void dateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateComboActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
        

          
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         String finalamount = jTextField8.getText();
        float billamount = Float.valueOf(finalamount);
        String cash = jTextField6.getText();
        float cashamount = Float.valueOf(cash);

        float val = billamount - cashamount;
        
        String val2 = String.valueOf(val);
        jTextField7.setText(val2);
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dateCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateCombo1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
          String fname = jComboBox3.getSelectedItem().toString();
        String fnames = String.valueOf(fname);

       StudentDetails dao = new StudentDetails();
       Student sp = dao.searchDetails(fnames);

        /* brandnametxt.setText(d.getName());
         suppIDbrandcmb.setSelectedItem(d.getSupplierId());
         supbrandNametxt.setText(d.getSupplierName());
         branddescriptiontxt.setText(d.getDescription());*/
     jComboBox3.setSelectedItem(String.valueOf(sp.getfname()));
       Course.setText(sp.getCourse()); 
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
           String Name = jComboBox3.getSelectedItem().toString();
        String Date = dateCombo1.getSelectedItem().toString();
          String course = Course.getText();
     String Amounts = jTextField2.getText();
        int Amount = Integer.valueOf(Amounts);
            
     
        
     Component rootPane = null;
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Save This Recode?");

        if (x == 0) {
            Payment cs = new Payment(Name,course,Date,Amount);

            PaymentDetails dao = new PaymentDetails();
            dao. addPayment(cs);
            jComboBox3.setSelectedItem("00");
         dateCombo1.setSelectedItem("00");
         Course.setText("");
    jTextField2.setText("");


            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
        jComboBox3.setSelectedItem("00");
         dateCombo1.setSelectedItem("00");
         Course.setText("");
    jTextField2.setText("");

        } else {
         jComboBox3.setSelectedItem("00");
         dateCombo1.setSelectedItem("00");
         Course.setText("");
    jTextField2.setText("");

            ;
        }



    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        loadPaymentTable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here
      String PId = jComboBox2.getSelectedItem().toString();
    int PIds = Integer.valueOf(PId);


    PaymentDetails dao = new PaymentDetails();
    Payment sp = dao.searchBalanceDetails(PIds);

    /* brandnametxt.setText(d.getName());
    suppIDbrandcmb.setSelectedItem(d.getSupplierId());
    supbrandNametxt.setText(d.getSupplierName());
    branddescriptiontxt.setText(d.getDescription());*/
    jComboBox2.setSelectedItem(String.valueOf(sp.getPId()));
    jTextField5.setText(sp.getStudentName());
    jTextField9.setText(sp.getCourse());
    jTextField8.setText(String.valueOf(sp.getAmount()));
    
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            String PId = jComboBox2.getSelectedItem().toString();
              int PIDS = Integer.valueOf(PId);
                 String StudentName = jTextField5.getText(); 
                 String Course = jTextField9.getText();
                         String Date = dateCombo.getSelectedItem().toString();
                         
          String Amount = jTextField8.getText();
        int Amounts = Integer.valueOf(Amount);  
        
        String Payed = jTextField6.getText();
        int Payeds = Integer.valueOf(Payed);
        
  String Balance = jTextField7.getText();

            
     
        
     Component rootPane = null;
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Save This Recode?");

        if (x == 0) {
            Payment cs = new Payment(PIDS,StudentName,Course,Date,Amounts,Payeds,Balance);

            PaymentDetails dao = new PaymentDetails();
            dao. addPaymentBalance(cs);
            jComboBox2.setSelectedItem("00");
         jTextField5.setText("");
           dateCombo.setSelectedItem("00");
        jTextField9.setText("");
  jTextField8.setText("00");
  jTextField6.setText("00");
 jTextField7.setText("00");
  
  
            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
             jComboBox2.setSelectedItem("00");
         jTextField5.setText("");
           dateCombo.setSelectedItem("00");
        jTextField9.setText("");
  jTextField8.setText("00");
  jTextField6.setText("00");
    jTextField7.setText("00");

        } else {
             jComboBox2.setSelectedItem("00");
         jTextField5.setText("");
           dateCombo.setSelectedItem("00");
        jTextField9.setText("");
  jTextField8.setText("00");
  jTextField6.setText("00");
    jTextField7.setText("00");

            ;
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
           loadPaymentBalanceTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void FullPaymentBalanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FullPaymentBalanceMouseClicked
        // TODO add your handling code here:
            DefaultTableModel Student  = (DefaultTableModel )FullPaymentBalance.getModel();
   jComboBox2.setSelectedItem(Student.getValueAt(FullPaymentBalance.getSelectedRow(),1).toString());
      jTextField5.setText(Student.getValueAt(FullPaymentBalance.getSelectedRow(),2).toString()); 
 dateCombo.setSelectedItem(Student.getValueAt(FullPaymentBalance.getSelectedRow(),3).toString()); 
jTextField9.setText(Student.getValueAt(FullPaymentBalance.getSelectedRow(),4).toString());  
    jTextField8.setText(Student.getValueAt(FullPaymentBalance.getSelectedRow(),5).toString());  
        jTextField6.setText(Student.getValueAt(FullPaymentBalance.getSelectedRow(),6).toString());  
            jTextField7.setText(Student.getValueAt(FullPaymentBalance.getSelectedRow(),7).toString());  
    }//GEN-LAST:event_FullPaymentBalanceMouseClicked

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
       if (clickcount == 0) {
            clickcount = 1;
            jButton3.setEnabled(false);
            jButton2.setEnabled(false);
            starrowcount = jTable1.getRowCount();

            new Thread(new Runnable() {

                @Override
                public void run() {
                    try {

                        if (jTable1.getRowCount() == 0) {

                            JOptionPane.showMessageDialog(null, "Please search first", "error",
                                    JOptionPane.ERROR_MESSAGE);
                            clickcount = 0;
                            jButton2.setEnabled(true);

                            jButton3.setEnabled(true);
                        } else if (jTable1.getRowCount() == 1) {
                            String body = jTextArea1.getText();
                            if (body.isEmpty()) {
                                JOptionPane.showMessageDialog(null, "Please type massage body", "error",
                                        JOptionPane.ERROR_MESSAGE);
                                clickcount = 0;
                                jButton2.setEnabled(true);
                                jButton3.setEnabled(true);

                            } else {
                                BasicConfigurator.configure();
                                clickcount = 1;
                                jButton3.setEnabled(false);
                                jButton2.setEnabled(false);
                                Object oo = jTable1.getValueAt(0, 4);
                                mobile = (String) oo;

                                for (int i = 0; i <= jProgressBar1.getMaximum(); i++) {
                                    jProgressBar1.setVisible(true);
                                    jProgressBar1.setValue(i);

                                    if (i == 1) {
                                        jProgressBar1.setString("Starting Sending to " + mobile);
                                        // lbl_loading.setText("Welcome " + txt_un.getSelectedItem());
                                    }
                                    if (i == 20) {
                                        jProgressBar1.setString(" Please Wait. Sending to" + mobile);
                                        // lbl_loading.setText("Welcome " + txt_un.getSelectedItem() + ",Arranging Databases");
                                    }
                                    if (i == 40) {
                                        jProgressBar1.setString(" Please Wait...Sending to " + mobile);
                                        // lbl_loading.setText("Welcome " + txt_un.getSelectedItem() + ",Loading Images");
                                    }
                                    if (i == 60) {
                                        jProgressBar1.setString(" Please Wait......Sending to " + mobile);
                                        // i = 80;
                                    }
                                    if (i == 80) {
                                        jProgressBar1.setString(" Please Wait..........Sending to " + mobile);

                                        //  lbl_loading.setText("Welcome " + txt_un.getSelectedItem() + ",Loading Home Page");
                                    }
                                    if (i == 100) {
                                        ModamSMS app = new ModamSMS("");
                                        body += "\n -- STUDENT MANAGEMENT SYSTEM --";
                                        app.sendMessage(mobile, body);
                                        //   ArrayList sendBulkMessage = app.sendBulkMessage(numbers, jTextField2.getText());

                                        if (kk) {
                                            jProgressBar1.setVisible(false);

                                         //   DataBase_Connection.putdata("INSERT INTO sms_history_auto (mem_id,name,messagec,mobile,send_date,stime) VALUES ('" + jTable1.getValueAt(0, 1) + "','" + jTable1.getValueAt(0, 3) + "','" + jTextField2.getText() + "','" + mobile + "','" + date.getText() + "','" + timel.getText() + "')");

                                            jProgressBar1.setString(" Send Success To " + mobile);
                                            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
                                            dtm.removeRow(0);

                                            JOptionPane.showMessageDialog(null, "" + " " + "Send Success", "SMS INFO", JOptionPane.INFORMATION_MESSAGE);
                                            jButton3.setEnabled(true);
                                            jButton2.setEnabled(true);
                                            jButton2.setEnabled(true);
                                            clickcount = 0;
                                        } else {
                                            jButton3.setEnabled(true);
                                            jButton2.setEnabled(true);

                                            clickcount = 0;
                                            JOptionPane.showMessageDialog(null, "Messege Not Sent Trying Faild, Please Resend", "SMS INFO", JOptionPane.ERROR_MESSAGE);
                                         jProgressBar1.setVisible(false);
                                        }

                                    }

                                    try {
                                        Thread.sleep(15);
                                    } catch (Exception e) {
                                        System.out.println(e);
                                    }
                                }

                            }

//JOptionPane.showMessageDialog(null, "one");
                        } else {
                            String body = jTextArea1.getText();
                            if (body.isEmpty()) {
                                JOptionPane.showMessageDialog(null, "Please type massage body");
                                clickcount = 0;
                                jButton2.setEnabled(true);
                                jButton3.setEnabled(true);
                            } else {
                                BasicConfigurator.configure();
                                clickcount = 1;
                                jButton3.setEnabled(false);
                                jButton2.setEnabled(false);
                                ArrayList<String> numbers = new ArrayList();

                                for (int ii = 0; ii < starrowcount; ii++) {

                                    Object oo = jTable1.getValueAt(ii, 2);
                                    String numm = (String) oo;

                                    numbers.add(ii, numm);
                                    //  JOptionPane.showMessageDialog(null, ii);

                                }

                                for (int i = 0; i <= jProgressBar1.getMaximum(); i++) {
                                    jProgressBar1.setVisible(true);
                                    jProgressBar1.setValue(i);

                                    if (i == 1) {
                                        jProgressBar1.setString("Starting Sending");
                                        // lbl_loading.setText("Welcome " + txt_un.getSelectedItem());
                                    }
                                    if (i == 20) {
                                        jProgressBar1.setString(" Please Wait. Sending");
                                        // lbl_loading.setText("Welcome " + txt_un.getSelectedItem() + ",Arranging Databases");
                                    }
                                    if (i == 40) {
                                        jProgressBar1.setString(" Please Wait...Sending");
                                        // lbl_loading.setText("Welcome " + txt_un.getSelectedItem() + ",Loading Images");
                                    }
                                    if (i == 60) {
                                        jProgressBar1.setString(" Please Wait......Sending");
                                        // i = 80;
                                    }
                                    if (i == 80) {
                                        jProgressBar1.setString(" Please Wait..........Sending");

                                        //  lbl_loading.setText("Welcome " + txt_un.getSelectedItem() + ",Loading Home Page");
                                    }
                                    if (i == 100) {

                                        ModamSMS app = new ModamSMS(get_port());
                                        body += "\n -- STUDENT MANAGEMENT SYSTEM --";
                                    app.sendBulkMessage(numbers, body);
                                        //jProgressBar1.setString(" Please Wait..........Sending to " + ModamSMS.unumber);

                                        if (kk) {
                                            JOptionPane.showMessageDialog(null, "All Messages Sent success ", "SMS INFO", JOptionPane.INFORMATION_MESSAGE);
                                            jButton3.setEnabled(true);
                                            jButton2.setEnabled(true);
                                            clickcount = 0;
                                        } else {

                                            jButton3.setEnabled(true);
                                            jButton2.setEnabled(true);
                                            clickcount = 0;
                                            JOptionPane.showMessageDialog(null, "Messege Not Sent Trying Faild, Please Resend", "SMS INFO", JOptionPane.ERROR_MESSAGE);
                                         jProgressBar1.setVisible(false);
                                        }

                                    }

                                    try {
                                        Thread.sleep(15);
                                    } catch (Exception e) {
                                        System.out.println(e);
                                    }
                                }

                            }

                            // JOptionPane.showMessageDialog(null, ">one");  
                        }

                        // JOptionPane.showMessageDialog(null, senderName+password1);
                        // ss //  toatal_amount = toatal_amount + Double.parseDouble(jTable1.getValueAt(ii, 5).toString());
                        //   Total_due = Total_due + Double.parseDouble(jTable1.getValueAt(ii, 6).toString());
                    } catch (Exception ex) {
                        jButton3.setEnabled(true);
                        jButton2.setEnabled(true);
                        clickcount = 0;
                        //  JOptionPane.showMessageDialog(null, "Message Not Send to" + name + "(" + mobile + ")", "Warning", JOptionPane.ERROR_MESSAGE);
                        JOptionPane.showMessageDialog(null, ex + " Error happen");
                        StringWriter sw = new StringWriter();
                        ex.printStackTrace(new PrintWriter(sw));

                        writfile(sw.toString());
                        jProgressBar1.setVisible(false);

                        ex.printStackTrace();

                    }
                }

                //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }).start();

        }  // TODO add your handling code here:
    }//GEN-LAST:event_sendActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String PId = jComboBox2.getSelectedItem().toString();
              int PIDS = Integer.valueOf(PId);
                 String StudentName = jTextField5.getText(); 
                 String Course = jTextField9.getText();
                         String Date = dateCombo.getSelectedItem().toString();
                         
          String Amount = jTextField8.getText();
        int Amounts = Integer.valueOf(Amount);  
        
        String Payed = jTextField6.getText();
        int Payeds = Integer.valueOf(Payed);
        
  String Balance = jTextField7.getText();

            
     
        
     Component rootPane = null;
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Save This Recode?");

        if (x == 0) {
            Payment cs = new Payment(PIDS,StudentName,Course,Date,Amounts,Payeds,Balance);

            PaymentDetails dao = new PaymentDetails();
            dao.updatepayment(cs);
            jComboBox2.setSelectedItem("00");
         jTextField5.setText("");
           dateCombo.setSelectedItem("00");
        jTextField9.setText("");
  jTextField8.setText("00");
  jTextField6.setText("00");
 jTextField7.setText("00");
  
  
            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
             jComboBox2.setSelectedItem("00");
         jTextField5.setText("");
           dateCombo.setSelectedItem("00");
        jTextField9.setText("");
  jTextField8.setText("00");
  jTextField6.setText("00");
    jTextField7.setText("00");

        } else {
             jComboBox2.setSelectedItem("00");
         jTextField5.setText("");
           dateCombo.setSelectedItem("00");
        jTextField9.setText("");
  jTextField8.setText("00");
  jTextField6.setText("00");
    jTextField7.setText("00");

            ;
        }


        
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Amount;
    private javax.swing.JTextField Course;
    private javax.swing.JTable FullPaymentBalance;
    private org.freixas.jcalendar.JCalendarCombo dateCombo;
    private org.freixas.jcalendar.JCalendarCombo dateCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton send;
    // End of variables declaration//GEN-END:variables
}
