/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIDesigns;
import Method.Grades;
import Method.GradeDetails;
import Method.StudentDetails;
import Method.Student;
import java.awt.Component;
import java.util.Vector;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Home-PC
 */
public class StudentGrade extends javax.swing.JPanel {
  private Vector<Vector<String>> data;
    private Vector<String> header;
     private Component rootPane;
        private Vector<String>Grade;
            private Vector<Vector<String>>courseydata; 
    /**
     * Creates new form Grade
     */
    public StudentGrade() {
        initComponents();
       fillStudentID();
          
           header = new Vector<String>();
        header.add("Batch_No");
        header.add("sid");
        header.add("Grade");
        header.add("Semester");
         header.add("Student_Name");
         header.add("year"); 
          header.add("Course");
          loadGradeTable();
          
           loadGradeTable();
      ;  
    }
    private void loadcourseTable() {

        Grade= new Vector<String>();
         Grade.add("Batch_No");
       Grade.add("sid");
       Grade.add("Grade");
        Grade.add("Semester");
        Grade.add("Student_Name");
        Grade.add("year"); 
          Grade.add("Course");
   
        GradeDetails dao = new GradeDetails();
       courseydata = dao.getGradeDetails();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(courseydata,  Grade));
        jScrollPane1.setViewportView(jTable1);
 }
    private void loadGradeTable() {

        GradeDetails dao = new GradeDetails();
        data = dao.getGradeDetails();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                data, header));
        jScrollPane1.setViewportView(jTable1);
    }
    private void fillStudentID() {
       StudentDetails dao = new StudentDetails();
        ArrayList NameList = dao.getStudent();

        Iterator i = NameList.iterator();

        while (i.hasNext()) {
           stid.addItem(i.next());
        }

        String csName = stid.getSelectedItem().toString();
 
    }
  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gradestxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateCombo = new org.freixas.jcalendar.JCalendarCombo();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Coursetxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Semestertxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Batchtxt = new javax.swing.JTextField();
        Course_Notxt = new javax.swing.JTextField();
        Student_Nametxt = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        stid = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1090, 660));
        setRequestFocusEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(Gradestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 240, 30));

        jLabel3.setText("Student Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        dateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateComboActionPerformed(evt);
            }
        });
        add(dateCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 240, 30));

        jLabel8.setBackground(new java.awt.Color(0, 153, 51));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Student Grades Details");
        jLabel8.setOpaque(true);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1090, 50));

        jLabel4.setText("Course_No ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel5.setText("Grade");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        jLabel2.setText("Batch_No");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jLabel7.setText("Semester");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Home-PC\\Documents\\StudentRegSystem\\src\\Image\\1460830381_Save.ico")); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabel6.setText("Year");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        Coursetxt.setBackground(new java.awt.Color(204, 204, 204));
        Coursetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursetxtActionPerformed(evt);
            }
        });
        add(Coursetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 240, 30));

        jLabel10.setText("Course");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));
        add(Semestertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 240, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Batch", "StudentID", "Student_Name", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 990, 150));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Apps-system-software-update-icon.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete-icon.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));
        add(Batchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 240, 30));

        Course_Notxt.setBackground(new java.awt.Color(204, 204, 204));
        add(Course_Notxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 240, 30));

        Student_Nametxt.setBackground(new java.awt.Color(204, 204, 204));
        add(Student_Nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 240, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Refresh-icon.png"))); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Find");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 90, -1));

        jLabel9.setText("Student Id");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        jPanel1.add(stid, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 240, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1050, 70));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1090, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void dateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateComboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        String sid = stid.getSelectedItem().toString();
        int sids = Integer.valueOf(sid);
        String Batch_No = Batchtxt.getText();  
        String Student_Names = Student_Nametxt.getText();
        String code = Course_Notxt.getText();
        String Grade = Gradestxt.getText();  
        String Semester = Semestertxt.getText();
        String year = dateCombo.getSelectedItem().toString();
        String Course = Coursetxt.getText();
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Save This Recode?");

        if (x == 0) {
            Grades cs = new Grades(Batch_No,sids,code,Grade,Semester,Student_Names,year,Course);

            GradeDetails dao = new GradeDetails();
            dao. addgrades(cs);
            stid.setSelectedItem("");
            Batchtxt.setText("");
            Student_Nametxt.setText("");
            Course_Notxt.setText("");
            Gradestxt.setText("");
            Semestertxt.setText("");
            dateCombo.setSelectedItem("");
              Coursetxt.setText("");
            
            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
             stid.setSelectedItem("");
            Batchtxt.setText("");
            Student_Nametxt.setText("");
            Course_Notxt.setText("");
            Gradestxt.setText("");
            Semestertxt.setText("");
            dateCombo.setSelectedItem("");
              Coursetxt.setText("");
            
        } else {
             stid.setSelectedItem("");
            Batchtxt.setText("");
            Student_Nametxt.setText("");
            Course_Notxt.setText("");
            Gradestxt.setText("");
            Semestertxt.setText("");
            dateCombo.setSelectedItem("");
              Coursetxt.setText("");
            
            ;
            
            Student_Nametxt.setEnabled(false);
        }  
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String sid = stid.getSelectedItem().toString();
        int sids = Integer.valueOf(sid);
        String Batch_No = Batchtxt.getText();  
        String Student_Names = Student_Nametxt.getText();
        String code = Course_Notxt.getText();
        String Grade = Gradestxt.getText();  
        String Semester = Semestertxt.getText();
        String year = dateCombo.getSelectedItem().toString();
        String Course = Coursetxt.getText();
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Delete This Recode?");

        if (x == 0) {
            /* EmployeeDetails em;
            em = new EmployeeDetails(emppid, lname, con1, con2, address, des);

            dao.updateEmployee(em);
             *
             *
             *
             */
             Grades cs = new Grades(Batch_No,sids,code,Grade,Semester,Student_Names,year,Course);

            GradeDetails dao = new GradeDetails();
             dao.deleteBrand(cs);
          stid.setSelectedItem("");
            Batchtxt.setText("");
            Student_Nametxt.setText("");
            Course_Notxt.setText("");
            Gradestxt.setText("");
            Semestertxt.setText("");
            dateCombo.setSelectedItem("");
              Coursetxt.setText("");

            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Delete Surccefull");

        } else if (x == 1) {
             Batchtxt.setText("");
            
        } else {
              Batchtxt.setText("");
          
            ;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel Grades  = (DefaultTableModel )jTable1.getModel();
         Batchtxt.setText(Grades.getValueAt(jTable1.getSelectedRow(),0).toString());
        Student_Nametxt.setText(Grades.getValueAt(jTable1.getSelectedRow(),1).toString());
     Course_Notxt.setText(Grades.getValueAt(jTable1.getSelectedRow(),2).toString());
     Gradestxt.setText(Grades.getValueAt(jTable1.getSelectedRow(),3).toString());
    Semestertxt.setText(Grades.getValueAt(jTable1.getSelectedRow(),4).toString());
   dateCombo.setSelectedItem(Grades.getValueAt(jTable1.getSelectedRow(),5).toString());  
   Coursetxt.setText(Grades.getValueAt(jTable1.getSelectedRow(),6).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String Batch_No = Batchtxt.getText(); 
       String sid = stid.getSelectedItem().toString();
        int sids = Integer.valueOf(sid);
         String code = Course_Notxt.getText();
         String Grade = Gradestxt.getText(); 
         String Semester = Semestertxt.getText();
        String Student_Names = Student_Nametxt.getText();
        String year = dateCombo.getSelectedItem().toString();
        String Course = Coursetxt.getText();
         
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You want to Change This Recode?");

        if (x == 0) {
            /* EmployeeDetails em;
            em = new EmployeeDetails(emppid, lname, con1, con2, address, des);

            dao.updateEmployee(em);
             *
             *
             *
             */
              Grades cs = new Grades(Batch_No,sids,code,Grade,Semester,Student_Names,year,Course);
       
             GradeDetails dao = new GradeDetails();
             dao.updateGrades(cs);
            stid.setSelectedItem("");
            Batchtxt.setText("");
            Student_Nametxt.setText("");
            Course_Notxt.setText("");
            Gradestxt.setText("");
            Semestertxt.setText("");
            dateCombo.setSelectedItem("");
             Coursetxt.setText("");       
               

            //Save to the database
            JOptionPane.showMessageDialog(rootPane, "Saved");

        } else if (x == 1) {
             stid.setSelectedItem("");
            Batchtxt.setText("");
            Student_Nametxt.setText("");
            Course_Notxt.setText("");
            Gradestxt.setText("");
            Semestertxt.setText("");
            dateCombo.setSelectedItem("");
              Coursetxt.setText("");
              
        } else {
              stid.setSelectedItem("");
            Batchtxt.setText("");
            Student_Nametxt.setText("");
            Course_Notxt.setText("");
            Gradestxt.setText("");
            Semestertxt.setText("");
            dateCombo.setSelectedItem("");
              Coursetxt.setText("");
              
               
            ;
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        loadcourseTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
            String Id = stid.getSelectedItem().toString();
        int supid = Integer.valueOf(Id);

       GradeDetails dao = new  GradeDetails();
       Student sp = dao.searchDetails(supid);

        /* brandnametxt.setText(d.getName());
         suppIDbrandcmb.setSelectedItem(d.getSupplierId());
         supbrandNametxt.setText(d.getSupplierName());
         branddescriptiontxt.setText(d.getDescription());*/
      
        stid.setSelectedItem(String.valueOf(sp.getsid()));
        Student_Nametxt.setText(sp.getfname());
        Course_Notxt.setText(sp.getcode());
        Coursetxt.setText(sp.getCourse());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void CoursetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CoursetxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Batchtxt;
    private javax.swing.JTextField Course_Notxt;
    private javax.swing.JTextField Coursetxt;
    private javax.swing.JTextField Gradestxt;
    private javax.swing.JTextField Semestertxt;
    private javax.swing.JTextField Student_Nametxt;
    private org.freixas.jcalendar.JCalendarCombo dateCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox stid;
    // End of variables declaration//GEN-END:variables
}
